version: '3.5'
networks:
  my-network-name:
    name: workshop
services:
  mongodb:
    container_name: workshop_mongo
    image: mongo:3.6
    command: mongod --smallfiles --quiet --logpath=/dev/null
    networks:
      - my-network-name